#!/bin/bash

LatestVERSION="28"

# freshen the basis
docker image pull php:8.0-apache-bullseye
docker image pull php:8.1-apache-bullseye

# manual autobuild
for VERSION in \
    "28" \
    "29" \
    "27" \
    "26" \
    "25" \
    "24" \
    "23" \
    ;
do
    echo "VERSION $VERSION"
    LATEST=
    [ "${LatestVERSION}" == "${VERSION}" ] && LATEST="-t neffets/nextcloud:latest"
    docker build -t neffets/nextcloud:${VERSION} ${LATEST} -f ${VERSION}/apache/Dockerfile ${VERSION}/apache/ || exit
    docker push neffets/nextcloud:${VERSION}
    [ -s "${LATEST}" ] && docker push neffets/nextcloud:latest
done

