#!/bin/bash

LatestVERSION="29"

# freshen the basis
docker image pull php:8.1-apache-bookworm
docker image pull php:8.2-apache-bookworm

# manual autobuild
for VERSION in \
    "30" \
    "29" \
    "28" \
    "29" \
    "27" \
    "26" \
    ;
do
    echo "VERSION $VERSION"
    LATEST=
    [ "${LatestVERSION}" == "${VERSION}" ] && LATEST="-t neffets/nextcloud:latest"
    docker build -t neffets/nextcloud:${VERSION} ${LATEST} -f ${VERSION}/apache/Dockerfile ${VERSION}/apache/ || exit
    docker push neffets/nextcloud:${VERSION}
    [ -s "${LATEST}" ] && docker push neffets/nextcloud:latest
done

