#!/bin/bash

LatestVERSION="21"

# freshen the basis
docker image pull php:7.4-apache-buster

# manual autobuild
for VERSION in \
    "18" \
    "19" \
    "20" \
    "21" \
    "22" \
    ;
do
    echo "VERSION $VERSION"
    LATEST=
    [ "${LatestVERSION}" == "${VERSION}" ] && LATEST="-t neffets/nextcloud:latest"
    docker build -t neffets/nextcloud:${VERSION} ${LATEST} -f ${VERSION}/apache/Dockerfile ${VERSION}/apache/
    docker push neffets/nextcloud:${VERSION}
    [ -s "${LATEST}" ] && docker push neffets/nextcloud:latest
done

